spring:
  application:
    name: did-ticketing
  datasource:
    url: jdbc:mysql://localhost:13306/user?serverTimezone=UTC&useSSL=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1 # HikariCP 유효성 검사 추가
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: create # 오직 테스트 환경에서만
    generate-ddl: true # 오직 테스트 환경에서만 (spring.jpa.generate-ddl)
    show-sql: true
    open-in-view: false

jwt:
  secretKey: pyokemonDidTicketingSecretKey123456789012345678901234567890
  accessTokenValidityInMilliseconds: 3600000
  refreshTokenValidityInMilliseconds: 86400000

# 블록체인 관련 설정
blockchain:
  ethereum:
    # 로컬 Ganache 또는 테스트넷 URL
    url: http://localhost:8545
    # 관리자 계정 비밀키 (실제 환경에서는 환경변수 등으로 안전하게 관리해야 함)
    private-key: ${BLOCKCHAIN_ADMIN_PRIVATE_KEY:0x45b1f2ab2d1e68a22af571d0aabb0a9d99916c9b34ae6f2a0f17f2cd8db23bf0}
    # 이미 배포된 컨트랙트 주소 (없으면 자동 배포)
    contract-address: ${BLOCKCHAIN_CONTRACT_ADDRESS:0x0000000000000000000000000000000000000000}

server:
  port: 8080 